
// filepath: d:\InnoknowVex\STREAMIFY\frontend\src\constants\index.js
export const THEMES = [
  { name: "light", label: "Light", colors: ["#ffffff", "#5a67d8", "#8b5cf6", "#1a202c"] },
  { name: "dark", label: "Dark", colors: ["#1f2937", "#8b5cf6", "#ec4899", "#1a202c"] },
  { name: "cupcake", label: "Cupcake", colors: ["#f5f5f4", "#65c3c8", "#ef9fbc", "#291334"] },
  { name: "coffee", label: "Coffee", colors: ["#20161f", "#dd9866", "#497174", "#eeeeee"] },
  { name: "winter", label: "Winter", colors: ["#ffffff", "#0284c7", "#d946ef", "#0f172a"] },
  { name: "synthwave", label: "Synthwave", colors: ["#2d1b69", "#e779c1", "#58c7f3", "#f8f8f2"] },
  { name: "retro", label: "Retro", colors: ["#e4d8b4", "#ea6962", "#6aaa64", "#282425"] },
  { name: "valentine", label: "Valentine", colors: ["#f0d6e8", "#e96d7b", "#a991f7", "#37243c"] },
  { name: "halloween", label: "Halloween", colors: ["#0d0d0d", "#ff7800", "#006400", "#ffffff"] },
  { name: "garden", label: "Garden", colors: ["#e9e7e7", "#ec4899", "#16a34a", "#374151"] },
  // Add other themes here...
];
export const LANGUAGES = [
  "English",
  "Telugu",
  "Tamil",
  "Malayalam",
  "Kannada",
  "Bengali",
  "Marathi",
  "Gujarati",
  "Spanish",
  "French",
  "German",
  "Mandarin",
  "Japanese",
  "Korean",
  "Hindi",
  "Russian",
  "Portuguese",
  "Arabic",
  "Italian",
  "Turkish",
  "Dutch",
];

export const LANGUAGE_TO_FLAG = {
  english: "gb",
  telugu: "in",
  tamil: "in",
  malayalam: "in",
  kannada: "in",  
  bengali: "in",
  marathi: "in",
  gujarati: "in", 
  spanish: "es",
  french: "fr",
  german: "de",
  mandarin: "cn",
  japanese: "jp",
  korean: "kr",
  hindi: "in",
  russian: "ru",
  portuguese: "pt",
  arabic: "sa",
  italian: "it",
  turkish: "tr",
  dutch: "nl",
};